### ISSUE TITLE
Confirm of New Data Aquisition

### ISSUE THREAD

**Issue by BrunoRichard98** [eclipse-tocandira/Tocandira-front#3]
When it saves a new IP address and a new PORT, it doesn't show that the requisition it was done.

**Comment by pedro-ricardo** [comment]
The Data Acquisition card was removed and added a new home screen to configure the collectors.

**Comment by pedro-ricardo** [comment]
The merge in https://github.com/eclipse-tocandira/Tocandira-front/commit/1395d40d1f733e8699612fc595de83a04d2f578e fixed this.
